user www-data;
worker_processes 1;
pid /run/nginx.pid;
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

        root /app/public;  # Cambiado a /app
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string =404;  # Redirige todo a index.php
        }

        # Regla para /clientes/
        location /clientes/ {
            alias /app/public/externalaccess/www/;  # Ruta dentro del contenedor
            try_files $uri $uri/ /clientes/index.php?$query_string;  # Para soportar PHP
            index index.html index.php;
    
            # Procesar PHP dentro de /clientes/
            location ~ \.php$ {
                include fastcgi_params;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_param SCRIPT_FILENAME $request_filename;
            }
        }

        # location ~ \.php$ {
        #     include fastcgi_params;
        #     fastcgi_pass 127.0.0.1:9000;
        #     fastcgi_index index.php;
        #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # }

        location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            if (!-f $document_root$fastcgi_script_name) {
                return 404;
            }

            # Mitigate https://httpoxy.org/ vulnerabilities
            fastcgi_param HTTP_PROXY "";

            # root           /app/public;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            # Dolibarr Rest API path support
            fastcgi_param  PATH_INFO       $fastcgi_path_info;
            fastcgi_param  PATH_TRANSLATED $document_root$fastcgi_script_name;

            # # Faster upload
            fastcgi_pass_request_body off;
            client_body_in_file_only clean;
            fastcgi_param  REQUEST_BODY_FILE $request_body_file;
            client_body_temp_path /dev/shm/client_body_temp;

            # Longer timeout
            fastcgi_connect_timeout 60;
            fastcgi_send_timeout 180;
            fastcgi_read_timeout 180;
            fastcgi_buffer_size 128k;
            fastcgi_buffers 4 256k;
            fastcgi_busy_buffers_size 256k;
            fastcgi_temp_file_write_size 256k;
            fastcgi_intercept_errors on;

            gzip on;
        }

        location ~ /\.ht {
            deny all;
        }

    }

    gzip on;                                    # Habilita gzip
    gzip_comp_level 6;                          # Nivel de compresión (1-9)
    gzip_min_length 256;                        # Mínimo tamaño del archivo a comprimir
    gzip_types text/plain text/css              # Tipos de contenido a comprimir
            application/json application/javascript 
            application/x-javascript text/xml
            application/xml application/xml+rss 
            text/javascript application/vnd.ms-fontobject 
            application/font-sfnt;           # Agrega más tipos si es necesario
    gzip_proxied any;                           # Comprime incluso cuando se usa un proxy
    gzip_disable "msie6";                       # Deshabilita gzip para navegadores antiguos
    gzip_vary on;                               # Agrega encabezado Vary para proxies

}
